DROP TABLE IF EXISTS COMPANY CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS EMPLOYEE CASCADE;
DROP TABLE IF EXISTS LEADS CASCADE;
DROP TABLE IF EXISTS CALL CASCADE;
DROP TABLE IF EXISTS REP_DETAIL CASCADE;
DROP TABLE IF EXISTS APPOINTMENT CASCADE;
DROP TABLE IF EXISTS RESULT_APPOINTMENT CASCADE;
DROP TABLE IF EXISTS EMPLOYEE_REPDETAIL CASCADE;
DROP TABLE IF EXISTS SCHEDULE CASCADE;
DROP TABLE IF EXISTS SCHEDULE_REPDETAIL CASCADE;
DROP TABLE IF EXISTS APPROACH_TYPE CASCADE;
DROP TABLE IF EXISTS APPRTYPE_REPDETAIL CASCADE;
DROP TABLE IF EXISTS CHARACTERISTICSAPP CASCADE;
DROP TABLE IF EXISTS CHARACTAPP_REPDETAIL CASCADE;
DROP TABLE IF EXISTS AUTHENTICATION CASCADE;
DROP TABLE IF EXISTS ROLE CASCADE;
DROP TABLE IF EXISTS LICENSE CASCADE;
DROP TABLE IF EXISTS LICENSE_CUSTOMER CASCADE;
DROP TABLE IF EXISTS RESULT_CALL CASCADE;
DROP TABLE IF EXISTS REASONS_NOTQUALIFY CASCADE;
DROP TABLE IF EXISTS PROSPECT_CATEGORY CASCADE;
DROP TABLE IF EXISTS FILE_UPLOAD_LOG CASCADE;
DROP TABLE IF EXISTS FILE_UPLOAD_ERROR_DETAILS CASCADE;
DROP TABLE IF EXISTS RESULT_APPOINTMENT CASCADE;

COMMIT;

DROP SEQUENCE IF EXISTS company_id_seq CASCADE;
DROP SEQUENCE IF EXISTS users_id_seq CASCADE;
DROP SEQUENCE IF EXISTS employee_id_seq CASCADE;
DROP SEQUENCE IF EXISTS leads_id_seq CASCADE;
DROP SEQUENCE IF EXISTS call_id_seq CASCADE;
DROP SEQUENCE IF EXISTS rep_detail_id_seq CASCADE;
DROP SEQUENCE IF EXISTS appointment_id_seq CASCADE;
DROP SEQUENCE IF EXISTS employee_repdetail_id_seq CASCADE;
DROP SEQUENCE IF EXISTS schedule_repdetail_id_seq CASCADE;
DROP SEQUENCE IF EXISTS apprtype_repdetail_id_seq CASCADE;
DROP SEQUENCE IF EXISTS charactapp_repdetail_id_seq CASCADE;
DROP SEQUENCE IF EXISTS authentication_id_seq CASCADE;
DROP SEQUENCE IF EXISTS license_id_seq CASCADE;
DROP SEQUENCE IF EXISTS license_customer_id_seq CASCADE;
DROP SEQUENCE IF EXISTS file_upload_id_seq CASCADE;


COMMIT;

CREATE TABLE ROLE (
    ID INTEGER NOT NULL UNIQUE,
    DESCRIPTION VARCHAR NOT NULL,
    CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP
);

CREATE TABLE RESULT_CALL (
    ID INTEGER NOT NULL UNIQUE,
    DESCRIPTION VARCHAR NOT NULL,
    CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP
);

CREATE TABLE REASONS_NOTQUALIFY (
    ID INTEGER NOT NULL UNIQUE,
    DESCRIPTION VARCHAR NOT NULL,
    CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP
);

CREATE TABLE PROSPECT_CATEGORY (
    ID INTEGER NOT NULL UNIQUE,
    DESCRIPTION VARCHAR NOT NULL,
    CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP
);


CREATE TABLE COMPANY (
    ID INTEGER NOT NULL UNIQUE,
    NAME VARCHAR NOT NULL,
    PHONE VARCHAR NOT NULL,
    OPTIONAL_PHONE VARCHAR,
    ZIP VARCHAR NOT NULL,
    CITY VARCHAR NOT NULL,
    COUNTRY VARCHAR NOT NULL,
    ADDRESS VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL UNIQUE,
    OPTIONAL_EMAIL VARCHAR,
    ECONOMY_ACTIVITY VARCHAR,
    NOTES VARCHAR,
    STATUS VARCHAR NOT NULL,
    CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP,
    PRIMARY KEY (ID,NAME)
);

CREATE TABLE USERS (
    ID INTEGER NOT NULL UNIQUE,
    LOGIN VARCHAR NOT NULL UNIQUE,
    PASSWORD VARCHAR NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    STATUS VARCHAR, --ACTIVO, EN MORA, SUSPENDIDO (POR NO PAGO, O POR DADA DE BAJA)
    COMPANY_ID INTEGER,
    USER_NAME VARCHAR,
    CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP,
    PRIMARY KEY (ID,LOGIN),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);

CREATE TABLE EMPLOYEE (
    ID INTEGER NOT NULL UNIQUE,
    NAME VARCHAR NOT NULL,
    PHONE VARCHAR NOT NULL,
    OPTIONAL_PHONE VARCHAR,
    ZIP VARCHAR,
    CITY VARCHAR,
    COUNTRY VARCHAR NOT NULL,
    ADDRESS VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL UNIQUE,
    OPTIONAL_EMAIL VARCHAR,
    NOTES VARCHAR,
    STATUS VARCHAR,
    COMPANY_ID INTEGER,
    USERS_ID INTEGER UNIQUE,
    CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP,
    PRIMARY KEY (ID,EMAIL),
    FOREIGN KEY (USERS_ID) REFERENCES USERS (ID),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID)
);

CREATE TABLE REP_DETAIL	(
  	ID	INTEGER NOT NULL UNIQUE,
  	NAME	VARCHAR NOT NULL,
  	PHONE	VARCHAR NOT NULL UNIQUE,
  	OPTIONAL_PHONE VARCHAR,
  	ZIP VARCHAR,
    CITY VARCHAR,
    COUNTRY VARCHAR NOT NULL,
    ADDRESS VARCHAR NOT NULL,
  	EMAIL	VARCHAR NOT NULL UNIQUE,
  	OPTIONAL_EMAIL VARCHAR,
  	AREA_TRABAJO VARCHAR,
  	REP_DETAIL_PREDECESSOR	INTEGER,
  	COMPANY_ID	INTEGER NOT NULL,
  	USERS_ID INTEGER NOT NULL,
  	DATA_FREQUENCY VARCHAR, /*DIARIO-SEMANAL*/
  	DATA_QT_APROX INTEGER,
  	COOKING BOOLEAN,
  	ADDRESS_COOKING VARCHAR,
  	CITY_APPOINTMENTS VARCHAR,
  	CITY_AUTH_APPOINTMENTS VARCHAR,
  	REPORT_SHARED BOOLEAN,
  	REPORT_CALL BOOLEAN,
  	REPORT_MESSAGE BOOLEAN,
  	CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP,
    PRIMARY KEY (ID,PHONE),
    FOREIGN KEY (REP_DETAIL_PREDECESSOR) REFERENCES REP_DETAIL (ID),
    FOREIGN KEY (USERS_ID) REFERENCES USERS (ID),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID)
);

CREATE TABLE SCHEDULE	(
	ID	INTEGER NOT NULL UNIQUE,
	DAY VARCHAR,
	HOUR VARCHAR,
	CREATED_ON TIMESTAMP,
  UPDATED_ON TIMESTAMP,
	PRIMARY KEY (ID)
);

CREATE TABLE SCHEDULE_REPDETAIL(
    ID INTEGER NOT NULL UNIQUE,
	  SCHEDULE_ID	INTEGER NOT NULL,
	  USER_REPDETAIL_ID	INTEGER NOT NULL,
	  SELECTED BOOLEAN,
	  CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE (ID),
    FOREIGN KEY (USER_REPDETAIL_ID) REFERENCES USERS (ID)
);

CREATE TABLE APPROACH_TYPE (
    ID INTEGER NOT NULL UNIQUE,
    DESCRIPTION VARCHAR NOT NULL,
    CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP
);

CREATE TABLE APPRTYPE_REPDETAIL (
    ID INTEGER NOT NULL UNIQUE,
	  APPROACH_TYPE_ID	INTEGER NOT NULL,
	  USER_REPDETAIL_ID	INTEGER NOT NULL,
	  CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (APPROACH_TYPE_ID) REFERENCES APPROACH_TYPE (ID),
    FOREIGN KEY (USER_REPDETAIL_ID) REFERENCES USERS (ID)
);

CREATE TABLE CHARACTERISTICSAPP (
    ID INTEGER NOT NULL UNIQUE,
    DESCRIPTION VARCHAR NOT NULL,
    CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP
);

CREATE TABLE CHARACTAPP_REPDETAIL (
    ID INTEGER NOT NULL UNIQUE,
	  CHARACTERISTICSAPP_ID	INTEGER NOT NULL,
	  USER_REPDETAIL_ID	INTEGER NOT NULL,
	  CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (CHARACTERISTICSAPP_ID) REFERENCES CHARACTERISTICSAPP (ID),
    FOREIGN KEY (USER_REPDETAIL_ID) REFERENCES USERS (ID)
);

CREATE TABLE FILE_UPLOAD_LOG (
  ID INTEGER NOT NULL UNIQUE,
  FILE_NAME VARCHAR NOT NULL,
  TOTAL_RECORDS INTEGER,
  TOTAL_SUCCESFUL INTEGER,
  TOTAL_ERROR INTEGER,
  STATUS INTEGER, -- 0: RECIBIDO, 1: PROCESADO CON FALLA (CARGA PARCIAL), 2: PROCESADO EXITOSO, 3; FALLIDO
  CREATED_ON TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE FILE_UPLOAD_ERROR_DETAILS (
  ID INTEGER NOT NULL UNIQUE,
  FILE_UPLOAD_LOG_FK INTEGER NOT NULL,
  LINE_NUMBER INTEGER NOT NULL,
  LINE_VALUE VARCHAR,
  ERROR_MESSAGE VARCHAR,
  CREATED_ON TIMESTAMP,
  FOREIGN KEY (FILE_UPLOAD_LOG_FK) REFERENCES FILE_UPLOAD_LOG (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE LEADS (
  ID INTEGER NOT NULL UNIQUE,
  DATE_DATA VARCHAR NOT NULL,
  RATING VARCHAR,  -- * ** ***
  NAME VARCHAR NOT NULL,
  MARITAL_STATUS VARCHAR, -- Soltero, Casado, Viuda, Separado, Pareja
  SPOUSE_NAME VARCHAR,
  PHONE VARCHAR NOT NULL,
  ZIP VARCHAR NOT NULL,
  CITY VARCHAR NOT NULL,
  USER_REPDETAIL_ID INTEGER NOT NULL, --Para identificar que REP_DETAIL (vendedor) lo esta atendiendo
  APPROACH_TYPE_ID INTEGER NOT NULL,  --Abordaje, Toque de Puerta, 4-14, Referido, Cliente
  PROSPECT_CATEGORY_ID INTEGER NOT NULL,  --Prospecto, Alfitrion 4-14, Referido 4-14, Cliente, Referido para promoción
  APPROACH_PLACE VARCHAR,
  APPROACH_NOTES VARCHAR NOT NULL,
  APPROACH_NOTES_414 VARCHAR NOT NULL,
  ADDRESS VARCHAR,
  STATUS INTEGER NOT NULL, -- 0-NUEVO, -1 INACTIVO (TELEFONO NO EXISTENTE), 1 ACTIVO
  HOST BOOLEAN, -- BOOLEAN
  HOST_ID INTEGER,
  COMPANY_ID INTEGER NOT NULL,
  USER_EMPLOYEE_ID INTEGER, --Para identificar que TELEMARKETER lo esta atendiendo
  FILE_UPLOAD_LOG_FK INTEGER, --Foreign key to file upload logs
  CREATED_ON TIMESTAMP,
  UPDATED_ON TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (FILE_UPLOAD_LOG_FK) REFERENCES FILE_UPLOAD_LOG (ID),
  FOREIGN KEY (USER_EMPLOYEE_ID) REFERENCES USERS (ID),
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID),
  FOREIGN KEY (APPROACH_TYPE_ID) REFERENCES APPROACH_TYPE (ID),
  --FOREIGN KEY (USER_REPDETAIL_ID) REFERENCES USERS (ID),
  --FOREIGN KEY (HOST_ID) REFERENCES LEADS (ID),
  FOREIGN KEY (PROSPECT_CATEGORY_ID) REFERENCES PROSPECT_CATEGORY (ID),
  CONSTRAINT unique_lead_constraint UNIQUE (NAME, PHONE, USER_REPDETAIL_ID)
);

CREATE TABLE CALL (
    ID INTEGER NOT NULL UNIQUE,
    RESULT_CALL_ID INTEGER,
    REASONS_NOTQUALIFY_ID INTEGER,
    NOTES VARCHAR,
    LEADS_ID INTEGER,
    USERS_REPDETAIL_ID INTEGER,
    COMPANY_ID INTEGER,
    USERS_EMPLOYEE_ID INTEGER,
    CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP,
    PRIMARY KEY (ID,LEADS_ID),
    FOREIGN KEY (USERS_REPDETAIL_ID) REFERENCES USERS (ID),
    FOREIGN KEY (LEADS_ID) REFERENCES LEADS (ID),
    FOREIGN KEY (USERS_EMPLOYEE_ID) REFERENCES USERS (ID),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID),
    FOREIGN KEY (RESULT_CALL_ID) REFERENCES RESULT_CALL (ID),
    FOREIGN KEY (REASONS_NOTQUALIFY_ID) REFERENCES REASONS_NOTQUALIFY (ID)
);


CREATE TABLE RESULT_APPOINTMENT (
  ID INTEGER NOT NULL UNIQUE,
  DESCRIPTION VARCHAR NOT NULL,
  CREATED_ON TIMESTAMP,
  UPDATED_ON TIMESTAMP
);


CREATE TABLE APPOINTMENT(
  	ID	INTEGER NOT NULL UNIQUE,
  	DATE_APPOINT TIMESTAMP NOT NULL,
  	RESULT_APPOINTMENT_ID INTEGER,
  	COORD_COMMENTS VARCHAR,
  	TELEOPE_COMMENTS VARCHAR,
  	STATUS INTEGER,
  	USERS_REPDETAIL_ID INTEGER,
    COMPANY_ID INTEGER,
    USERS_EMPLOYEE_ID INTEGER,
  	LEADS_ID	INTEGER NOT NULL,
  	CALL_ID	INTEGER NOT NULL,
  	CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP,
    PRIMARY KEY (ID,DATE_APPOINT, USERS_REPDETAIL_ID, LEADS_ID),
    FOREIGN KEY (USERS_REPDETAIL_ID) REFERENCES USERS (ID),
    FOREIGN KEY (LEADS_ID) REFERENCES LEADS (ID),
    FOREIGN KEY (USERS_EMPLOYEE_ID) REFERENCES USERS (ID),
    FOREIGN KEY (CALL_ID) REFERENCES CALL (ID),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID),
    FOREIGN KEY (RESULT_APPOINTMENT_ID) REFERENCES RESULT_APPOINTMENT (ID)
);

CREATE TABLE EMPLOYEE_REPDETAIL(
  	ID INTEGER NOT NULL UNIQUE,
  	USER_EMPLOYEE_ID INTEGER,
  	COMPANY_ID INTEGER NOT NULL,
  	USER_REPDETAIL_ID INTEGER,
  	CREATED_ON TIMESTAMP,
    UPDATED_ON TIMESTAMP,
	  PRIMARY KEY (ID),
    FOREIGN KEY (USER_EMPLOYEE_ID) REFERENCES USERS (ID),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID),
    FOREIGN KEY (USER_REPDETAIL_ID) REFERENCES USERS (ID)
);

CREATE TABLE LICENSE (
	ID INTEGER NOT NULL UNIQUE,
	NAME VARCHAR NOT NULL,
	QT_USERS INTEGER,
	PRICE FLOAT,
	CREATED_ON TIMESTAMP,
  UPDATED_ON TIMESTAMP,
	PRIMARY KEY (ID)
);


CREATE TABLE LICENSE_CUSTOMER	(
	ID	INTEGER NOT NULL UNIQUE,
	LICENSE_ID INTEGER NOT NULL,
	USERS_ID INTEGER,
	COMPANY_ID INTEGER,
	CREATED_ON TIMESTAMP,
  UPDATED_ON TIMESTAMP,
	PRIMARY KEY (ID),
  FOREIGN KEY (LICENSE_ID) REFERENCES LICENSE (ID),
  FOREIGN KEY (USERS_ID) REFERENCES USERS (ID),
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID)
);

CREATE TABLE AUTHENTICATION (
  ID INTEGER NOT NULL UNIQUE,
  USERS_ID INTEGER NOT NULL,
  TOKEN UUID NOT NULL, -- crear indice
  EXPIRATION_TIME TIMESTAMP NOT NULL,
  CREATED_ON TIMESTAMP,
  UPDATED_ON TIMESTAMP,
  FOREIGN KEY (USERS_ID) REFERENCES USERS (ID),
  PRIMARY KEY (ID)
);

COMMIT;

CREATE SEQUENCE company_id_seq
       INCREMENT BY 1027
       MINVALUE 107
       CACHE 1
       NO CYCLE
       OWNED BY company.id;

CREATE SEQUENCE users_id_seq
       INCREMENT BY 1077
       MINVALUE 117
       CACHE 1
       NO CYCLE
       OWNED BY users.id;

CREATE SEQUENCE employee_id_seq
       INCREMENT BY 1037
       MINVALUE 109
       CACHE 1
       NO CYCLE
       OWNED BY employee.id;

CREATE SEQUENCE leads_id_seq
       INCREMENT BY 1097
       MINVALUE 119
       CACHE 1
       NO CYCLE
       OWNED BY leads.id;

CREATE SEQUENCE call_id_seq
       INCREMENT BY 1097
       MINVALUE 119
       CACHE 1
       NO CYCLE
       OWNED BY call.id;

CREATE SEQUENCE Rep_Detail_id_seq
       INCREMENT BY 1097
       MINVALUE 119
       CACHE 1
       NO CYCLE
       OWNED BY Rep_Detail.id;

CREATE SEQUENCE appointment_id_seq
       INCREMENT BY 1097
       MINVALUE 119
       CACHE 1
       NO CYCLE
       OWNED BY appointment.id;

CREATE SEQUENCE Employee_RepDetail_id_seq
       INCREMENT BY 1097
       MINVALUE 119
       CACHE 1
       NO CYCLE
       OWNED BY Employee_RepDetail.id;

CREATE SEQUENCE schedule_repdetail_id_seq
       INCREMENT BY 1067
       MINVALUE 115
       CACHE 1
       NO CYCLE
       OWNED BY schedule_repdetail.id;

CREATE SEQUENCE apprtype_repdetail_id_seq
       INCREMENT BY 1127
       MINVALUE 119
       CACHE 1
       NO CYCLE
       OWNED BY apprtype_repdetail.id;

CREATE SEQUENCE charactapp_repdetail_id_seq
       INCREMENT BY 1057
       MINVALUE 113
       CACHE 1
       NO CYCLE
       OWNED BY charactapp_repdetail.id;

CREATE SEQUENCE authentication_id_seq
       INCREMENT BY 1087
       MINVALUE 119
       CACHE 1
       NO CYCLE
       OWNED BY authentication.id;

CREATE SEQUENCE license_id_seq
       INCREMENT BY 1047
       MINVALUE 111
       CACHE 1
       NO CYCLE
       OWNED BY license.id;

CREATE SEQUENCE license_customer_id_seq
       INCREMENT BY 1047
       MINVALUE 111
       CACHE 1
       NO CYCLE
       OWNED BY license_customer.id;

CREATE SEQUENCE file_upload_id_seq
      INCREMENT BY 104
      MINVALUE 111
      CACHE 1
      NO CYCLE
      OWNED BY file_upload_log.id;

COMMIT;

--Datos de configuración

--company
INSERT INTO COMPANY(ID, NAME,PHONE,OPTIONAL_PHONE,ZIP,CITY,COUNTRY,ADDRESS,EMAIL,OPTIONAL_EMAIL,ECONOMY_ACTIVITY,
  NOTES,STATUS,CREATED_ON,UPDATED_ON)
VALUES(107,'TRP','+584267371966','', '1070','CARACAS','VENEZUELA','','coordinaciongeneraltrp@gmail.com','',
  'TELEMARKETING/CALL CENTER','N/A','ACTIVO',NOW(),NOW());

--Roles

INSERT INTO ROLE (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES(1,'Gerente',NOW(),NOW());
INSERT INTO ROLE (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (2,'Supervisor/Coordinador',NOW(),NOW());
INSERT INTO ROLE (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (3,'Telemarketer',NOW(),NOW());
INSERT INTO ROLE (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (4,'Representante',NOW(),NOW());

--Approach Type
INSERT INTO APPROACH_TYPE (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (1,'ABORDAJE',NOW(),NOW());
INSERT INTO APPROACH_TYPE (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (2,'TOQUE DE PUERTA',NOW(),NOW());
INSERT INTO APPROACH_TYPE (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (3,'4 en 14',NOW(),NOW());
INSERT INTO APPROACH_TYPE (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (4,'REFERIDO',NOW(),NOW());
INSERT INTO APPROACH_TYPE (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (5,'CLIENTE',NOW(),NOW());

--Result Call
INSERT INTO RESULT_CALL (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (1,'CITA',NOW(),NOW());
INSERT INTO RESULT_CALL (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (2,'NO CONTEST/VB',NOW(),NOW());
INSERT INTO RESULT_CALL (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (3,'LLAMAR LUEGO',NOW(),NOW());
INSERT INTO RESULT_CALL (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (4,'EQUIVOCADO',NOW(),NOW());
INSERT INTO RESULT_CALL (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (5,'NO CALIFICA PARA DEMO',NOW(),NOW());
INSERT INTO RESULT_CALL (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (6,'TIENE REPRESENTANTE RP',NOW(),NOW());
INSERT INTO RESULT_CALL (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (7,'ESTA MOLESTO CON RP',NOW(),NOW());
INSERT INTO RESULT_CALL (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (8,'NÚMERO NO EXISTE',NOW(),NOW());

--REASONS LEADS NOT QUALIFY FOR APPOINTMENT
INSERT INTO REASONS_NOTQUALIFY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (1,'TRANCA AL ESCUCHAR RP DESPUES DE DOS LLAMADAS',NOW(),NOW());
INSERT INTO REASONS_NOTQUALIFY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (2,'NO TIENE TIEMPO POR SU TRABAJO',NOW(),NOW());
INSERT INTO REASONS_NOTQUALIFY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (3,'NO TIENE TRABAJO',NOW(),NOW());
INSERT INTO REASONS_NOTQUALIFY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (4,'NO DECIDE SOLA Y SU PAREJA NO ESTA EN CASA',NOW(),NOW());
INSERT INTO REASONS_NOTQUALIFY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (5,'NO ESTA INTERESADA Y TRANCA',NOW(),NOW());
INSERT INTO REASONS_NOTQUALIFY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (6,'YA LE HICIERON DEMOSTRACION Y NO DESEA RP',NOW(),NOW());
INSERT INTO REASONS_NOTQUALIFY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (7,'COMPRO HACE MENOS DE 6 MESES',NOW(),NOW());
INSERT INTO REASONS_NOTQUALIFY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (8,'TIENE POCO TIEMPO EN EL PAIS Y NO TIENE DOMICILIO FIJO',NOW(),NOW());
INSERT INTO REASONS_NOTQUALIFY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (9,'TRABAJA SOLO POR DIAS',NOW(),NOW());

--- CATEGORIA PROSPECTO
INSERT INTO PROSPECT_CATEGORY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (1,'PROSPECTO',NOW(),NOW());
INSERT INTO PROSPECT_CATEGORY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (2,'ANFITRION 4-14',NOW(),NOW());
INSERT INTO PROSPECT_CATEGORY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (3,'REFERIDO 4-14',NOW(),NOW());
INSERT INTO PROSPECT_CATEGORY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (4,'REFERIDO PARA PROMOCION',NOW(),NOW());
INSERT INTO PROSPECT_CATEGORY (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (5,'CLIENTE',NOW(),NOW());

-- PREFERENCIAS APLICACION DE CITAS
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (1,'CASADO QUE SOLO UNO TRABAJE PERO QUE POSIBLEMENTE ESTEN AMBOS EN LA CITA',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (2,'HOMBRE CASADO SIN PRESENCIA DE LA ESPOSA',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (3,'MUJER CASADA QUE NO TRABAJE SIN PRESENCIA DEL ESPOSO, PERO DECIDE SOLA',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (4,'PERSONA QUE TIENE PENSION',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (5,'MUJERES CASADAS QUE TRABAJEN, SIN PRESENCIA DE SU ESPOSO',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (6,'SOLTEROS (A) QUE TRABAJEN',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (7,'VIUDOS QUE TRABAJEN',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (8,'SOLTERAS (O) CON HIJOS QUE TRABAJEN',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (9,'SOLTERAS (O) SIN HIJOS',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (10,'TRP ADQUIRIDOS EN MENOS DE TRES MESES',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (11,'NACIONALIDADES EN ESPECIFICO',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (12,'YA TIENEN PREMIOS O HAN IDO A UNA PRESENTACION RP HACE MENOS DE UN MES',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (13,'TIENEN REPRESENTANTE PERO TIENE TIEMPO SIN VERLO',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (14,'COMPRARON EL PAQUETE COMPLETO DE PRODUCTOS (CAJA DE PRODUCTOS)',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (15,'TRABAJAN DE NOCHE PERO PUEDEN SER VISITADOS A PRIMERA HORA DE LA MAÑANA',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (16,'TRABAJAN DE NOCHE PERO PUEDEN SER VISITADOS A PRIMERA HORA DE LA MAÑANA',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (17,'COLOQUE OTRAS QUE USTEDE CONSIDERE RELEVANTES',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (18,'CASADOS QUE TRABAJEN LOS DOS PERO QUE ESTEN JUNTOS EN LA PRESENTACION',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (19,'CASADOS QUE TRABAJE UNO DE LOS DOS PERO QUE ESTEN JUNTOS EN LA PRESENTACION',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (20,'SOLTERAS QUE TRABAJEN QUE VIVAN CON PADRES QUE ESTEN EN LA PRESENTACION JUNTOS',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (21,'TRP ADQUIRIDOS EN MAS DE OCHO MESES',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (22,'MADRES SOLTERAS QUE TRABAJEN O TENGAN PENSION',NOW(),NOW());
INSERT INTO CHARACTERISTICSAPP (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
  VALUES (23,'PADRES SOLTEROS O VIUDOS QUE TRABAJEN QUE VIVAN CON HIJOS',NOW(),NOW());


--schedule

INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(1, 'LUNES', '8am a 10am', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(2, 'LUNES', '10 am a 12m', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(3, 'LUNES', '12m a 2pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(4, 'LUNES', '2pm a 4pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(5, 'LUNES', '4pm a 6pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(6, 'LUNES', '6pm a 8pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(7, 'LUNES', '8pm a 10pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(8, 'MARTES', '8am a 10am', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(9, 'MARTES', '10 am a 12m', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(10, 'MARTES', '12m a 2pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(11, 'MARTES', '2pm a 4pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(12, 'MARTES', '4pm a 6pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(13, 'MARTES', '6pm a 8pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(14, 'MARTES', '8pm a 10pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(15, 'MIERCOLES', '8am a 10am', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(16, 'MIERCOLES', '10 am a 12m', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(17, 'MIERCOLES', '12m a 2pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(18, 'MIERCOLES', '2pm a 4pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(19, 'MIERCOLES', '4pm a 6pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(20, 'MIERCOLES', '6pm a 8pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(21, 'MIERCOLES', '8pm a 10pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(22, 'JUEVES', '8am a 10am', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(23, 'JUEVES', '10 am a 12m', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(24, 'JUEVES', '12m a 2pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(25, 'JUEVES', '2pm a 4pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(26, 'JUEVES', '4pm a 6pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(27, 'JUEVES', '6pm a 8pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(28, 'JUEVES', '8pm a 10pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(29, 'VIERNES', '8am a 10am', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(30, 'VIERNES', '10 am a 12m', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(31, 'VIERNES', '12m a 2pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(32, 'VIERNES', '2pm a 4pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(33, 'VIERNES', '4pm a 6pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(34, 'VIERNES', '6pm a 8pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(35, 'VIERNES', '8pm a 10pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(36, 'SABADO', '8am a 10am', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(37, 'SABADO', '10 am a 12m', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(38, 'SABADO', '12m a 2pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(39, 'SABADO', '2pm a 4pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(40, 'SABADO', '4pm a 6pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(41, 'SABADO', '6pm a 8pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(42, 'SABADO', '8pm a 10pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(43, 'DOMINGO', '8am a 10am', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(44, 'DOMINGO', '10 am a 12m', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(45, 'DOMINGO', '12m a 2pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(46, 'DOMINGO', '2pm a 4pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(47, 'DOMINGO', '4pm a 6pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(48, 'DOMINGO', '6pm a 8pm', NOW(), NOW());
INSERT INTO SCHEDULE (ID,DAY,HOUR,CREATED_ON,UPDATED_ON) VALUES(49, 'DOMINGO', '8pm a 10pm', NOW(), NOW());

-- Result appointment
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (1,'Cita Atendida con Demo',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (2,'Cita Atendida con Demo sin Venta',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (3,'Cita Atendida con Demo y Venta',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (4,'Cita Cancelada por el Prospecto',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (5,'Cita Cancelada por el Representante',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (6,'Cita Reagendada por el Prospecto',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (7,'Cita Reagendada por el Representante',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (8,'Cita No Atendida por Representante',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (9,'Cita No Califica para Demo',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (10,'Cita No atendida por Prospecto',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (11,'Cita con Demo sin Venta con 4 en 14',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (12,'Cita con Demo y Venta con 4 en 14',NOW(),NOW());
INSERT INTO RESULT_APPOINTMENT (ID, DESCRIPTION, CREATED_ON, UPDATED_ON)
VALUES (13,'Cita sin Demo con 4 en 14',NOW(),NOW());

COMMIT;